#!/usr/bin/env bash

if
  [[ -s "/home/hobe/.rvm/gems/ruby-2.1.5@global/environment" ]]
then
  source "/home/hobe/.rvm/gems/ruby-2.1.5@global/environment"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/hobe/.rvm/gems/ruby-2.1.5@global/environment'" >&2
  exit 1
fi
