# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1428510889);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1428511009);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1428522901);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1428510769);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1428514409);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 296960);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150125222326");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20150125222326");
user_pref("browser.startup.homepage_override.mstone", "35.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":4}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button-throttled\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":3,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1428079204759");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1428514998805");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1428515000989");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1428601400989");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1427818922111");
user_pref("datareporting.policy.firstRunTime", "1427818851809");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.firstPaint", 15375);
user_pref("datareporting.sessions.current.main", 713);
user_pref("datareporting.sessions.current.sessionRestored", 14933);
user_pref("datareporting.sessions.current.startTime", "1428746624740");
user_pref("datareporting.sessions.current.totalTime", 40);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.2", "{\"s\":1427880714774,\"a\":711,\"t\":580419,\"c\":false,\"m\":373,\"fp\":4784,\"sr\":6061}");
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 10);
user_pref("extensions.blocklist.pingCountVersion", 10);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"35.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"35.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.08.06.beta,ubufox%40ubuntu.com:3.0,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1428510890);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150402.01");
user_pref("extensions.lastAppVersion", "35.0.1");
user_pref("extensions.lastPlatformVersion", "35.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"35.0.1\",\"st\":1424288976000,\"mt\":1422226198000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"35.0.1\",\"st\":1422227014000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"35.0.1\",\"st\":1422227014000}},\"app-system-share\":{\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.08.06.beta\",\"st\":1424289188000,\"mt\":1407283796000},\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1424289188000,\"mt\":1420839872000},\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1424289189000,\"mt\":1397665356000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1424289189000,\"mt\":1390969638000}}}");
user_pref("gecko.buildID", "20150125222326");
user_pref("gecko.mstone", "35.0.1");
user_pref("idle.lastDailyNotification", 1428524710);
user_pref("loop.soft_start_ticket_number", 11761025);
user_pref("loop.throttled2", false);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1427818923);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1427818923);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.atsvc.enabled", false);
user_pref("network.http.atsvc.oe", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1428514998);
user_pref("places.history.expiration.transient_current_max_pages", 26309);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1427819736);
user_pref("toolkit.startup.last_success", 1428746625);
user_pref("toolkit.telemetry.previousBuildID", "20150125222326");
